# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars: 
  PROFILE_NAME: SoullessEngine

tasks:
  conan-generate:
    desc: Generate project Requirements
    cmd: conan install . --build=missing --profile={{.PROFILE_NAME}} --settings=compiler.cppstd=17
    
  conan-generate-rel:
    desc: Generate project Requirements for Release
    cmd: conan install . --build=missing --settings=compiler.cppstd=17

  conan-profile:
    desc: Generate project profile
    cmd: conan profile detect --name {{.PROFILE_NAME}}

  cmake:
    desc: Build Project files
    cmds:
      - cmake . {{.CLI_ARGS}} -DCMAKE_TOOLCHAIN_FILE="build/generators/conan_toolchain.cmake"

  make:
    desc: make Project files
    cmds:
      - task: conan-generate
      - task: cmake
      
  make-rel:
    desc: make Project files for Release
    cmds:
      - task: conan-generate-rel
      - task: cmake
        
  init:
    desc: One Time command to run the first time the porject is installed
    cmds:
      - task: conan-profile
      - task: make
