# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  conan-generate:
    desc: Generate project Requirements
    cmd: conan install . --build=missing

  conan-profile:
    desc: Generate project profile
    cmd: conan profile detect --force

  cmake:
    desc: Build Project files
    cmds:
      - cmake . {{.CLI_ARGS}} -DCMAKE_TOOLCHAIN_FILE="build/generators/conan_toolchain.cmake"

  make:
    desc: make Project files
    cmds:
      - task: conan-profile
      - task: conan-generate
      - task: cmake
